# Generated by Django 3.2.1 on 2021-05-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_matriz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matrizs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Matriz', to='account.matriz'),
            preserve_default=False,
        ),
    ]
