# Generated by Django 3.2.1 on 2021-06-01 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_matrizs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='matrizs',
        ),
        migrations.DeleteModel(
            name='Matriz',
        ),
    ]
