# Generated by Django 3.2.1 on 2021-06-14 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriz', '0001_initial'),
        ('account', '0004_auto_20210601_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matriz',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='matriz.matriz', verbose_name='Matriz'),
        ),
    ]
