# Generated by Django 3.2.1 on 2021-06-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_matriz'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pendente',
            field=models.BooleanField(default=False),
        ),
    ]
