# Generated by Django 3.2.1 on 2021-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo',
            field=models.CharField(choices=[[0, 'Administrador'], [1, 'Aluno'], [2, 'Professor']], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
