# Generated by Django 3.2.1 on 2021-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210505_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.IntegerField(choices=[[1, 'Administrador'], [2, 'Aluno'], [3, 'Professor']], max_length=1, verbose_name='Tipo de Usuário'),
        ),
    ]
