# Generated by Django 3.2.1 on 2021-05-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210505_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.IntegerField(choices=[[1, 'Administrador'], [2, 'Aluno'], [3, 'Professor']], verbose_name='Tipo de Usuário'),
        ),
    ]
