# Generated by Django 3.2.1 on 2021-05-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo',
            field=models.IntegerField(blank=True, choices=[[1, 'Administrador'], [2, 'Aluno'], [3, 'Professor']], verbose_name='Tipo de Usuário'),
        ),
    ]
