# Generated by Django 3.2.1 on 2021-06-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.DateField()),
                ('status', models.BooleanField()),
                ('carga_horaria', models.FloatField()),
            ],
        ),
    ]
